sudo: false
language: clojure
lein: lein2
script: $TEST
env:
  matrix:
  - TEST=lein2 test-clj
  - TEST=./scripts/test.sh
matrix:
  exclude:
    - env: TEST=./scripts/test.sh
      jdk: openjdk6
    - env: TEST=./scripts/test.sh
      jdk: openjdk7
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
node_js:
  - "0.10"
cache:
  directories:
  - "$HOME/.m2"
