sudo: false
language: clojure
lein: lein2
script: lein2 $TEST
env:
  matrix:
  - TEST=test-clj
  - TEST=test-node
matrix:
  exclude:
    - env: TEST=test-node
      jdk: openjdk6
    - env: TEST=test-node
      jdk: openjdk7
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk8
node_js:
  - "0.10"
cache:
  directories:
  - "$HOME/.m2"
